ATL = [
    ["AJ Griffin", "A Griffin", "4.56", "", "", ""],
    ["Bogdan Bogdanovic", "B Bogdanovic", "34.62", "", "", ""],
    ["Bruno Fernando", "B Fernando", "7.15", "", "", ""],
    ["Clint Capela", "C Capela", "31.3", "", "", ""],
    ["De'Andre Hunter", "D Hunter", "27.3", "", "", ""],
    ["Dejounte Murray", "D Murray", "42.72", "", "", ""],
    ["Garrison Mathews", "G Mathews", "8.39", "", "", ""],
    ["Jalen Johnson", "J Johnson", "37.34", "", "", ""],
    ["Kobe Bufkin", "K Bufkin", "3.45", "", "", ""],
    ["Mouhamed Gueye", "M Gueye", "1.5", "", "", ""],
    ["Onyeka Okongwu", "O Okongwu", "23.62", "", "", ""],
    ["Patty Mills", "P Mills", "8.42", "", "", ""],
    ["Saddiq Bey", "S Bey", "28.55", "", "", ""],
    ["Seth Lundy", "S Lundy", "2.86", "", "", ""],
    ["Trae Young", "T Young", "54.38", "", "", ""],
    ["Trent Forrest", "T Forrest", "7.98", "", "", ""],
    ["Wesley Matthews", "W Matthews", "7.48", "", "", ""],
]

BOS = [
    ["Al Horford", "A Horford", "27.41", "", "", ""],
    ["Dalano Banton", "D Banton", "5.95", "", "", ""],
    ["Derrick White", "D White", "37.9", "", "", ""],
    ["Drew Peterson", "D Peterson", "6.5", "", "", ""],
    ["JD Davison", "J Davison", "2.2", "", "", ""],
    ["Jaylen Brown", "J Brown", "41.03", "", "", ""],
    ["Jayson Tatum", "J Tatum", "51.78", "", "", ""],
    ["Jordan Walsh", "J Walsh", "3.75", "", "", ""],
    ["Jrue Holiday", "J Holiday", "34.2", "", "", ""],
    ["Kristaps Porzingis", "K Porzingis", "40.48", "", "", ""],
    ["Lamar Stevens", "L Stevens", "6.72", "", "", ""],
    ["Luke Kornet", "L Kornet", "14.93", "", "", ""],
    ["Neemias Queta", "N Queta", "13.21", "", "", ""],
    ["Oshae Brissett", "O Brissett", "10.1", "", "", ""],
    ["Payton Pritchard", "P Pritchard", "20.27", "", "", ""],
    ["Sam Hauser", "S Hauser", "20.08", "", "", ""],
    ["Svi Mykhailiuk", "S Mykhailiuk", "6.13", "", "", ""],
]

BKN = [
    ["Armoni Brooks", "A Brooks", "9.61", "", "", ""],
    ["Ben Simmons", "B Simmons", "32.73", "", "", ""],
    ["Cam Thomas", "C Thomas", "32.74", "", "", ""],
    ["Cameron Johnson", "C Johnson", "30.62", "", "", ""],
    ["Dariq Whitehead", "D Whitehead", "7.65", "", "", ""],
    ["Day'Ron Sharpe", "D Sharpe", "21.2", "", "", ""],
    ["Dennis Smith Jr.", "D Jr.", "21.16", "", "", ""],
    ["Dorian Finney-Smith", "D Finney-Smith", "24.16", "", "", ""],
    ["Harry Giles III", "H III", "6.05", "", "", ""],
    ["Jalen Wilson", "J Wilson", "9.74", "", "", ""],
    ["Keon Johnson", "K Johnson", "23.7", "", "", ""],
    ["Lonnie Walker IV", "L IV", "23.74", "", "", ""],
    ["Mikal Bridges", "M Bridges", "40.15", "", "", ""],
    ["Nic Claxton", "N Claxton", "34.83", "", "", ""],
    ["Noah Clowney", "N Clowney", "10.16", "", "", ""],
    ["Royce O'Neale", "R O'Neale", "23.45", "", "", ""],
    ["Spencer Dinwiddie", "S Dinwiddie", "31.48", "", "", ""],
    ["Trendon Watford", "T Watford", "12.79", "", "", ""],
]

CHA = [
    ["Amari Bailey", "A Bailey", "3.2", "", "", ""],
    ["Brandon Miller", "B Miller", "30.23", "", "", ""],
    ["Bryce McGowens", "B McGowens", "10.74", "", "", ""],
    ["Cody Martin", "C Martin", "21.64", "", "", ""],
    ["Frank Ntilikina", "F Ntilikina", "3.84", "", "", ""],
    ["Gordon Hayward", "G Hayward", "31.74", "", "", ""],
    ["Ish Smith", "I Smith", "10.79", "", "", ""],
    ["JT Thor", "J Thor", "9.52", "", "", ""],
    ["James Bouknight", "J Bouknight", "7.89", "", "", ""],
    ["LaMelo Ball", "L Ball", "50.62", "", "", ""],
    ["Leaky Black", "L Black", "6.39", "", "", ""],
    ["Mark Williams", "M Williams", "31.04", "", "", ""],
    ["Miles Bridges", "M Bridges", "42.23", "", "", ""],
    ["Nathan Mensah", "N Mensah", "7.34", "", "", ""],
    ["Nick Richards", "N Richards", "24.36", "", "", ""],
    ["Nick Smith Jr.", "N Jr.", "13.05", "", "", ""],
    ["P.J. Washington", "P Washington", "30.32", "", "", ""],
    ["Terry Rozier", "T Rozier", "45.68", "", "", ""],
    ["Theo Maledon", "T Maledon", "10.76", "", "", ""],
]

CHI = [
    ["Adama Sanogo", "A Sanogo", "4.8", "", "", ""],
    ["Alex Caruso", "A Caruso", "27.57", "", "", ""],
    ["Andre Drummond", "A Drummond", "22.76", "", "", ""],
    ["Ayo Dosunmu", "A Dosunmu", "20.87", "", "", ""],
    ["Coby White", "C White", "38.79", "", "", ""],
    ["Dalen Terry", "D Terry", "8.02", "", "", ""],
    ["DeMar DeRozan", "D DeRozan", "40.75", "", "", ""],
    ["Jevon Carter", "J Carter", "12.16", "", "", ""],
    ["Julian Phillips", "J Phillips", "3.57", "", "", ""],
    ["Nikola Vucevic", "N Vucevic", "40.05", "", "", ""],
    ["Onuralp Bitim", "O Bitim", "0.0", "", "", ""],
    ["Patrick Williams", "P Williams", "23.53", "", "", ""],
    ["Terry Taylor", "T Taylor", "4.9", "", "", ""],
    ["Torrey Craig", "T Craig", "18.06", "", "", ""],
    ["Zach LaVine", "Z LaVine", "37.59", "", "", ""],
]

CLE = [
    ["Caris LeVert", "C LeVert", "32.23", "", "", ""],
    ["Craig Porter Jr.", "C Jr.", "17.29", "", "", ""],
    ["Damian Jones", "D Jones", "5.9", "", "", ""],
    ["Darius Garland", "D Garland", "37.42", "", "", ""],
    ["Dean Wade", "D Wade", "18.58", "", "", ""],
    ["Donovan Mitchell", "D Mitchell", "55.08", "", "", ""],
    ["Emoni Bates", "E Bates", "5.7", "", "", ""],
    ["Evan Mobley", "E Mobley", "36.62", "", "", ""],
    ["Georges Niang", "G Niang", "19.91", "", "", ""],
    ["Isaac Okoro", "I Okoro", "20.39", "", "", ""],
    ["Isaiah Mobley", "I Mobley", "5.69", "", "", ""],
    ["Jarrett Allen", "J Allen", "36.25", "", "", ""],
    ["Max Strus", "M Strus", "31.87", "", "", ""],
    ["Pete Nance", "P Nance", "0.0", "", "", ""],
    ["Sam Merrill", "S Merrill", "18.85", "", "", ""],
    ["Tristan Thompson", "T Thompson", "11.03", "", "", ""],
    ["Ty Jerome", "T Jerome", "4.35", "", "", ""],
]

DAL = [
    ["A.J. Lawson", "A Lawson", "8.46", "", "", ""],
    ["Brandon Williams", "B Williams", "6.59", "", "", ""],
    ["Dante Exum", "D Exum", "20.36", "", "", ""],
    ["Dereck Lively II", "D II", "25.53", "", "", ""],
    ["Derrick Jones Jr.", "D Jr.", "22.52", "", "", ""],
    ["Dexter Dennis", "D Dennis", "10.56", "", "", ""],
    ["Dwight Powell", "D Powell", "13.61", "", "", ""],
    ["Grant Williams", "G Williams", "20.7", "", "", ""],
    ["Greg Brown III", "G III", "7.15", "", "", ""],
    ["Jaden Hardy", "J Hardy", "16.62", "", "", ""],
    ["Josh Green", "J Green", "19.35", "", "", ""],
    ["Kyrie Irving", "K Irving", "48.67", "", "", ""],
    ["Luka Doncic", "L Doncic", "69.32", "", "", ""],
    ["Markieff Morris", "M Morris", "7.61", "", "", ""],
    ["Maxi Kleber", "M Kleber", "12.05", "", "", ""],
    ["Olivier-Maxence Prosper", "O Prosper", "7.84", "", "", ""],
    ["Richaun Holmes", "R Holmes", "9.6", "", "", ""],
    ["Seth Curry", "S Curry", "10.18", "", "", ""],
    ["Tim Hardaway Jr.", "T Jr.", "32.39", "", "", ""],
]

DEN = [
    ["Aaron Gordon", "A Gordon", "30.72", "", "", ""],
    ["Braxton Key", "B Key", "3.34", "", "", ""],
    ["Christian Braun", "C Braun", "16.5", "", "", ""],
    ["Collin Gillespie", "C Gillespie", "4.66", "", "", ""],
    ["DeAndre Jordan", "D Jordan", "12.34", "", "", ""],
    ["Hunter Tyson", "H Tyson", "0.99", "", "", ""],
    ["Jalen Pickett", "J Pickett", "5.14", "", "", ""],
    ["Jamal Murray", "J Murray", "42.93", "", "", ""],
    ["Jay Huff", "J Huff", "1.57", "", "", ""],
    ["Julian Strawther", "J Strawther", "13.25", "", "", ""],
    ["Justin Holiday", "J Holiday", "9.57", "", "", ""],
    ["Kentavious Caldwell-Pope", "K Caldwell-Pope", "24.36", "", "", ""],
    ["Michael Porter Jr.", "M Jr.", "34.15", "", "", ""],
    ["Nikola Jokic", "N Jokic", "60.11", "", "", ""],
    ["Peyton Watson", "P Watson", "16.76", "", "", ""],
    ["Reggie Jackson", "R Jackson", "23.1", "", "", ""],
    ["Zeke Nnaji", "Z Nnaji", "7.97", "", "", ""],
]

DET = [
    ["Alec Burks", "A Burks", "23.88", "", "", ""],
    ["Ausar Thompson", "A Thompson", "23.47", "", "", ""],
    ["Bojan Bogdanovic", "B Bogdanovic", "35.36", "", "", ""],
    ["Cade Cunningham", "C Cunningham", "42.15", "", "", ""],
    ["Danilo Gallinari", "D Gallinari", "23.45", "", "", ""],
    ["Isaiah Livers", "I Livers", "12.77", "", "", ""],
    ["Isaiah Stewart", "I Stewart", "26.71", "", "", ""],
    ["Jaden Ivey", "J Ivey", "29.21", "", "", ""],
    ["Jalen Duren", "J Duren", "33.51", "", "", ""],
    ["James Wiseman", "J Wiseman", "13.2", "", "", ""],
    ["Jared Rhoden", "J Rhoden", "4.46", "", "", ""],
    ["Joe Harris", "J Harris", "6.73", "", "", ""],
    ["Kevin Knox II", "K II", "14.65", "", "", ""],
    ["Killian Hayes", "K Hayes", "21.46", "", "", ""],
    ["Malcolm Cazalon", "M Cazalon", "0.0", "", "", ""],
    ["Marcus Sasser", "M Sasser", "16.65", "", "", ""],
    ["Marvin Bagley III", "M III", "18.0", "", "", ""],
    ["Mike Muscala", "M Muscala", "12.47", "", "", ""],
    ["Monte Morris", "M Morris", "10.92", "", "", ""],
    ["Stanley Umude", "S Umude", "10.83", "", "", ""],
]

GSW = [
    ["Andrew Wiggins", "A Wiggins", "23.14", "", "", ""],
    ["Brandin Podziemski", "B Podziemski", "25.45", "", "", ""],
    ["Chris Paul", "C Paul", "29.36", "", "", ""],
    ["Cory Joseph", "C Joseph", "7.24", "", "", ""],
    ["Dario Saric", "D Saric", "24.7", "", "", ""],
    ["Draymond Green", "D Green", "30.49", "", "", ""],
    ["Gary Payton II", "G II", "15.2", "", "", ""],
    ["Gui Santos", "G Santos", "5.55", "", "", ""],
    ["Jerome Robinson", "J Robinson", "1.73", "", "", ""],
    ["Jonathan Kuminga", "J Kuminga", "26.32", "", "", ""],
    ["Kevon Looney", "K Looney", "18.27", "", "", ""],
    ["Klay Thompson", "K Thompson", "33.23", "", "", ""],
    ["Lester Quinones", "L Quinones", "7.47", "", "", ""],
    ["Moses Moody", "M Moody", "18.02", "", "", ""],
    ["Stephen Curry", "S Curry", "50.06", "", "", ""],
    ["Trayce Jackson-Davis", "T Jackson-Davis", "16.09", "", "", ""],
    ["Usman Garuba", "U Garuba", "2.25", "", "", ""],
]

HOU = [
    ["Aaron Holiday", "A Holiday", "14.31", "", "", ""],
    ["Alperen Sengun", "A Sengun", "44.81", "", "", ""],
    ["Amen Thompson", "A Thompson", "18.88", "", "", ""],
    ["Boban Marjanovic", "B Marjanovic", "6.08", "", "", ""],
    ["Cam Whitmore", "C Whitmore", "22.26", "", "", ""],
    ["Dillon Brooks", "D Brooks", "25.65", "", "", ""],
    ["Fred VanVleet", "F VanVleet", "43.71", "", "", ""],
    ["Jabari Smith Jr.", "J Jr.", "31.93", "", "", ""],
    ["Jae'Sean Tate", "J Tate", "13.11", "", "", ""],
    ["Jalen Green", "J Green", "34.21", "", "", ""],
    ["Jeff Green", "J Green", "11.67", "", "", ""],
    ["Jermaine Samuels Jr.", "J Jr.", "3.5", "", "", ""],
    ["Jock Landale", "J Landale", "7.62", "", "", ""],
    ["Nate Hinton", "N Hinton", "4.38", "", "", ""],
    ["Nate Williams", "N Williams", "6.18", "", "", ""],
    ["Reggie Bullock Jr.", "R Jr.", "6.61", "", "", ""],
    ["Tari Eason", "T Eason", "27.6", "", "", ""],
]

IND = [
    ["Aaron Nesmith", "A Nesmith", "27.48", "", "", ""],
    ["Andrew Nembhard", "A Nembhard", "20.46", "", "", ""],
    ["Ben Sheppard", "B Sheppard", "8.73", "", "", ""],
    ["Bennedict Mathurin", "B Mathurin", "25.68", "", "", ""],
    ["Bruce Brown", "B Brown", "26.84", "", "", ""],
    ["Buddy Hield", "B Hield", "29.01", "", "", ""],
    ["Daniel Theis", "D Theis", "2.0", "", "", ""],
    ["Isaiah Jackson", "I Jackson", "18.09", "", "", ""],
    ["Jalen Smith", "J Smith", "23.29", "", "", ""],
    ["James Johnson", "J Johnson", "5.26", "", "", ""],
    ["Jarace Walker", "J Walker", "12.91", "", "", ""],
    ["Jordan Nwora", "J Nwora", "10.66", "", "", ""],
    ["Kendall Brown", "K Brown", "3.05", "", "", ""],
    ["Myles Turner", "M Turner", "35.33", "", "", ""],
    ["Obi Toppin", "O Toppin", "23.2", "", "", ""],
    ["Oscar Tshiebwe", "O Tshiebwe", "7.15", "", "", ""],
    ["Pascal Siakam", "P Siakam", "39.44", "", "", ""],
    ["T.J. McConnell", "T McConnell", "21.67", "", "", ""],
    ["Tyrese Haliburton", "T Haliburton", "54.62", "", "", ""],
]

LAC = [
    ["Amir Coffey", "A Coffey", "11.59", "", "", ""],
    ["Bones Hyland", "B Hyland", "12.63", "", "", ""],
    ["Brandon Boston Jr.", "B Jr.", "7.82", "", "", ""],
    ["Daniel Theis", "D Theis", "16.99", "", "", ""],
    ["Ivica Zubac", "I Zubac", "29.69", "", "", ""],
    ["James Harden", "J Harden", "44.43", "", "", ""],
    ["Jordan Miller", "J Miller", "3.16", "", "", ""],
    ["Joshua Primo", "J Primo", "2.0", "", "", ""],
    ["KJ Martin", "K Martin", "12.05", "", "", ""],
    ["Kawhi Leonard", "K Leonard", "48.11", "", "", ""],
    ["Kobe Brown", "K Brown", "5.88", "", "", ""],
    ["Mason Plumlee", "M Plumlee", "17.06", "", "", ""],
    ["Moussa Diabate", "M Diabate", "6.7", "", "", ""],
    ["Nicolas Batum", "N Batum", "16.01", "", "", ""],
    ["Norman Powell", "N Powell", "24.29", "", "", ""],
    ["P.J. Tucker", "P Tucker", "7.33", "", "", ""],
    ["Paul George", "P George", "45.48", "", "", ""],
    ["Robert Covington", "R Covington", "19.19", "", "", ""],
    ["Russell Westbrook", "R Westbrook", "29.34", "", "", ""],
    ["Terance Mann", "T Mann", "18.12", "", "", ""],
    ["Xavier Moon", "X Moon", "3.95", "", "", ""],
]

LAL = [
    ["Alex Fudge", "A Fudge", "1.4", "", "", ""],
    ["Anthony Davis", "A Davis", "54.27", "", "", ""],
    ["Austin Reaves", "A Reaves", "32.38", "", "", ""],
    ["Cam Reddish", "C Reddish", "16.93", "", "", ""],
    ["Christian Wood", "C Wood", "18.31", "", "", ""],
    ["Colin Castleton", "C Castleton", "6.06", "", "", ""],
    ["D'Angelo Russell", "D Russell", "36.79", "", "", ""],
    ["D'Moi Hodge", "D Hodge", "4.25", "", "", ""],
    ["Dylan Windler", "D Windler", "6.89", "", "", ""],
    ["Gabe Vincent", "G Vincent", "15.1", "", "", ""],
    ["Jalen Hood-Schifino", "J Hood-Schifino", "3.99", "", "", ""],
    ["Jarred Vanderbilt", "J Vanderbilt", "16.46", "", "", ""],
    ["Jaxson Hayes", "J Hayes", "8.2", "", "", ""],
    ["LeBron James", "L James", "52.25", "", "", ""],
    ["Max Christie", "M Christie", "12.44", "", "", ""],
    ["Maxwell Lewis", "M Lewis", "1.24", "", "", ""],
    ["Rui Hachimura", "R Hachimura", "22.37", "", "", ""],
    ["Skylar Mays", "S Mays", "7.32", "", "", ""],
    ["Taurean Prince", "T Prince", "22.85", "", "", ""],
]

MEM = [
    ["Bismack Biyombo", "B Biyombo", "18.23", "", "", ""],
    ["David Roddy", "D Roddy", "18.62", "", "", ""],
    ["Derrick Rose", "D Rose", "17.44", "", "", ""],
    ["Desmond Bane", "D Bane", "46.27", "", "", ""],
    ["GG Jackson", "G Jackson", "17.38", "", "", ""],
    ["Ja Morant", "J Morant", "48.47", "", "", ""],
    ["Jacob Gilyard", "J Gilyard", "15.02", "", "", ""],
    ["Jake LaRavia", "J LaRavia", "7.55", "", "", ""],
    ["Jaren Jackson Jr.", "J Jr.", "40.92", "", "", ""],
    ["Jaylen Nowell", "J Nowell", "11.22", "", "", ""],
    ["John Konchar", "J Konchar", "16.81", "", "", ""],
    ["Kenneth Lofton Jr.", "K Jr.", "6.25", "", "", ""],
    ["Luke Kennard", "L Kennard", "24.77", "", "", ""],
    ["Marcus Smart", "M Smart", "32.49", "", "", ""],
    ["Matt Hurt", "M Hurt", "8.95", "", "", ""],
    ["Santi Aldama", "S Aldama", "26.79", "", "", ""],
    ["Scotty Pippen Jr.", "S Jr.", "23.64", "", "", ""],
    ["Shaquille Harrison", "S Harrison", "2.34", "", "", ""],
    ["Tosan Evbuomwan", "T Evbuomwan", "7.7", "", "", ""],
    ["Trey Jemison", "T Jemison", "14.6", "", "", ""],
    ["Vince Williams Jr.", "V Jr.", "24.7", "", "", ""],
    ["Xavier Tillman", "X Tillman", "20.67", "", "", ""],
    ["Ziaire Williams", "Z Williams", "17.23", "", "", ""],
]

MIA = [
    ["Bam Adebayo", "B Adebayo", "42.77", "", "", ""],
    ["Caleb Martin", "C Martin", "23.24", "", "", ""],
    ["Cole Swider", "C Swider", "4.79", "", "", ""],
    ["Dru Smith", "D Smith", "13.62", "", "", ""],
    ["Duncan Robinson", "D Robinson", "27.1", "", "", ""],
    ["Haywood Highsmith", "H Highsmith", "16.98", "", "", ""],
    ["Jaime Jaquez Jr.", "J Jr.", "26.26", "", "", ""],
    ["Jamal Cain", "J Cain", "12.22", "", "", ""],
    ["Jimmy Butler", "J Butler", "38.96", "", "", ""],
    ["Josh Richardson", "J Richardson", "22.11", "", "", ""],
    ["Kevin Love", "K Love", "23.79", "", "", ""],
    ["Kyle Lowry", "K Lowry", "24.9", "", "", ""],
    ["Nikola Jovic", "N Jovic", "16.61", "", "", ""],
    ["Orlando Robinson", "O Robinson", "12.32", "", "", ""],
    ["R.J. Hampton", "R Hampton", "3.46", "", "", ""],
    ["Terry Rozier", "T Rozier", "28.81", "", "", ""],
    ["Thomas Bryant", "T Bryant", "9.52", "", "", ""],
    ["Tyler Herro", "T Herro", "41.53", "", "", ""],
]

MIL = [
    ["AJ Green", "A Green", "6.86", "", "", ""],
    ["Andre Jackson Jr.", "A Jr.", "8.29", "", "", ""],
    ["Bobby Portis", "B Portis", "26.36", "", "", ""],
    ["Brook Lopez", "B Lopez", "35.2", "", "", ""],
    ["Cameron Payne", "C Payne", "14.19", "", "", ""],
    ["Chris Livingston", "C Livingston", "3.55", "", "", ""],
    ["Damian Lillard", "D Lillard", "47.96", "", "", ""],
    ["Giannis Antetokounmpo", "G Antetokounmpo", "58.57", "", "", ""],
    ["Jae Crowder", "J Crowder", "17.64", "", "", ""],
    ["Khris Middleton", "K Middleton", "32.56", "", "", ""],
    ["Lindell Wigginton", "L Wigginton", "1.8", "", "", ""],
    ["Malik Beasley", "M Beasley", "25.0", "", "", ""],
    ["MarJon Beauchamp", "M Beauchamp", "11.08", "", "", ""],
    ["Marques Bolden", "M Bolden", "1.2", "", "", ""],
    ["Pat Connaughton", "P Connaughton", "15.55", "", "", ""],
    ["Robin Lopez", "R Lopez", "2.09", "", "", ""],
    ["Thanasis Antetokounmpo", "T Antetokounmpo", "2.43", "", "", ""],
    ["TyTy Washington Jr.", "T Jr.", "3.6", "", "", ""],
]

MIN = [
    ["Anthony Edwards", "A Edwards", "46.12", "", "", ""],
    ["Daishen Nix", "D Nix", "2.74", "", "", ""],
    ["Jaden McDaniels", "J McDaniels", "21.79", "", "", ""],
    ["Jordan McLaughlin", "J McLaughlin", "10.1", "", "", ""],
    ["Josh Minott", "J Minott", "3.04", "", "", ""],
    ["Karl-Anthony Towns", "K Towns", "42.97", "", "", ""],
    ["Kyle Anderson", "K Anderson", "19.35", "", "", ""],
    ["Leonard Miller", "L Miller", "6.46", "", "", ""],
    ["Luka Garza", "L Garza", "3.68", "", "", ""],
    ["Mike Conley", "M Conley", "30.76", "", "", ""],
    ["Naz Reid", "N Reid", "26.37", "", "", ""],
    ["Nickeil Alexander-Walker", "N Alexander-Walker", "19.06", "", "", ""],
    ["Rudy Gobert", "R Gobert", "36.9", "", "", ""],
    ["Shake Milton", "S Milton", "9.96", "", "", ""],
    ["Troy Brown Jr.", "T Jr.", "10.3", "", "", ""],
    ["Wendell Moore Jr.", "W Jr.", "2.23", "", "", ""],
]

NOP = [
    ["Brandon Ingram", "B Ingram", "39.8", "", "", ""],
    ["CJ McCollum", "C McCollum", "42.39", "", "", ""],
    ["Cody Zeller", "C Zeller", "7.04", "", "", ""],
    ["Dereon Seabron", "D Seabron", "7.88", "", "", ""],
    ["Dyson Daniels", "D Daniels", "18.89", "", "", ""],
    ["E.J. Liddell", "E Liddell", "2.87", "", "", ""],
    ["Herbert Jones", "H Jones", "26.67", "", "", ""],
    ["Jeremiah Robinson-Earl", "J Robinson-Earl", "9.95", "", "", ""],
    ["Jonas Valanciunas", "J Valanciunas", "34.04", "", "", ""],
    ["Jordan Hawkins", "J Hawkins", "20.16", "", "", ""],
    ["Jose Alvarado", "J Alvarado", "17.82", "", "", ""],
    ["Kaiser Gates", "K Gates", "1.2", "", "", ""],
    ["Kira Lewis Jr.", "K Jr.", "6.78", "", "", ""],
    ["Larry Nance Jr.", "L Jr.", "18.57", "", "", ""],
    ["Matt Ryan", "M Ryan", "19.01", "", "", ""],
    ["Naji Marshall", "N Marshall", "17.9", "", "", ""],
    ["Trey Murphy III", "T III", "27.36", "", "", ""],
    ["Zion Williamson", "Z Williamson", "37.2", "", "", ""],
]

NYK = [
    ["Charlie Brown Jr.", "C Jr.", "1.9", "", "", ""],
    ["DaQuan Jeffries", "D Jeffries", "2.1", "", "", ""],
    ["Dmytro Skapintsev", "D Skapintsev", "0.0", "", "", ""],
    ["Donte DiVincenzo", "D DiVincenzo", "28.89", "", "", ""],
    ["Dylan Windler", "D Windler", "2.31", "", "", ""],
    ["Evan Fournier", "E Fournier", "12.06", "", "", ""],
    ["Immanuel Quickley", "I Quickley", "26.87", "", "", ""],
    ["Isaiah Hartenstein", "I Hartenstein", "26.02", "", "", ""],
    ["Jacob Toppin", "J Toppin", "1.35", "", "", ""],
    ["Jalen Brunson", "J Brunson", "47.78", "", "", ""],
    ["Jericho Sims", "J Sims", "5.97", "", "", ""],
    ["Josh Hart", "J Hart", "23.56", "", "", ""],
    ["Julius Randle", "J Randle", "44.84", "", "", ""],
    ["Malachi Flynn", "M Flynn", "3.48", "", "", ""],
    ["Miles McBride", "M McBride", "11.09", "", "", ""],
    ["Mitchell Robinson", "M Robinson", "27.11", "", "", ""],
    ["OG Anunoby", "O Anunoby", "34.37", "", "", ""],
    ["Precious Achiuwa", "P Achiuwa", "17.48", "", "", ""],
    ["Quentin Grimes", "Q Grimes", "16.7", "", "", ""],
    ["RJ Barrett", "R Barrett", "31.06", "", "", ""],
    ["Ryan Arcidiacono", "R Arcidiacono", "0.98", "", "", ""],
    ["Taj Gibson", "T Gibson", "5.47", "", "", ""],
]

OKC = [
    ["Aaron Wiggins", "A Wiggins", "12.61", "", "", ""],
    ["Aleksej Pokusevski", "A Pokusevski", "4.12", "", "", ""],
    ["Cason Wallace", "C Wallace", "16.56", "", "", ""],
    ["Chet Holmgren", "C Holmgren", "40.87", "", "", ""],
    ["Davis Bertans", "D Bertans", "7.24", "", "", ""],
    ["Isaiah Joe", "I Joe", "19.33", "", "", ""],
    ["Jalen Williams", "J Williams", "36.05", "", "", ""],
    ["Jaylin Williams", "J Williams", "12.89", "", "", ""],
    ["Josh Giddey", "J Giddey", "29.26", "", "", ""],
    ["Kenrich Williams", "K Williams", "13.58", "", "", ""],
    ["Keyontae Johnson", "K Johnson", "2.88", "", "", ""],
    ["Lindy Waters III", "L III", "7.32", "", "", ""],
    ["Luguentz Dort", "L Dort", "24.11", "", "", ""],
    ["Olivier Sarr", "O Sarr", "7.26", "", "", ""],
    ["Ousmane Dieng", "O Dieng", "9.06", "", "", ""],
    ["Shai Gilgeous-Alexander", "S Gilgeous-Alexander", "57.12", "", "", ""],
    ["Tre Mann", "T Mann", "9.21", "", "", ""],
    ["Vasilije Micic", "V Micic", "9.31", "", "", ""],
]

ORL = [
    ["Admiral Schofield", "A Schofield", "2.27", "", "", ""],
    ["Anthony Black", "A Black", "13.61", "", "", ""],
    ["Caleb Houstan", "C Houstan", "11.34", "", "", ""],
    ["Chuma Okeke", "C Okeke", "9.48", "", "", ""],
    ["Cole Anthony", "C Anthony", "26.27", "", "", ""],
    ["Franz Wagner", "F Wagner", "38.44", "", "", ""],
    ["Gary Harris", "G Harris", "16.84", "", "", ""],
    ["Goga Bitadze", "G Bitadze", "22.02", "", "", ""],
    ["Jalen Suggs", "J Suggs", "28.06", "", "", ""],
    ["Jett Howard", "J Howard", "3.75", "", "", ""],
    ["Joe Ingles", "J Ingles", "16.05", "", "", ""],
    ["Jonathan Isaac", "J Isaac", "17.58", "", "", ""],
    ["Kevon Harris", "K Harris", "0.2", "", "", ""],
    ["Markelle Fultz", "M Fultz", "22.84", "", "", ""],
    ["Moritz Wagner", "M Wagner", "21.02", "", "", ""],
    ["Paolo Banchero", "P Banchero", "43.48", "", "", ""],
    ["Trevelin Queen", "T Queen", "10.55", "", "", ""],
    ["Wendell Carter Jr.", "W Jr.", "26.26", "", "", ""],
]

PHI = [
    ["Danny Green", "D Green", "3.45", "", "", ""],
    ["Danuel House Jr.", "D Jr.", "9.72", "", "", ""],
    ["De'Anthony Melton", "D Melton", "30.7", "", "", ""],
    ["Filip Petrusev", "F Petrusev", "1.2", "", "", ""],
    ["Furkan Korkmaz", "F Korkmaz", "6.04", "", "", ""],
    ["Jaden Springer", "J Springer", "9.35", "", "", ""],
    ["Javonte Smart", "J Smart", "0.0", "", "", ""],
    ["Joel Embiid", "J Embiid", "64.81", "", "", ""],
    ["KJ Martin", "K Martin", "4.85", "", "", ""],
    ["Kelly Oubre Jr.", "K Jr.", "27.71", "", "", ""],
    ["Kenneth Lofton Jr.", "K Jr.", "0.4", "", "", ""],
    ["Marcus Morris Sr.", "M Sr.", "14.53", "", "", ""],
    ["Mo Bamba", "M Bamba", "13.41", "", "", ""],
    ["Nicolas Batum", "N Batum", "20.6", "", "", ""],
    ["P.J. Tucker", "P Tucker", "13.54", "", "", ""],
    ["Patrick Beverley", "P Beverley", "17.17", "", "", ""],
    ["Paul Reed", "P Reed", "17.8", "", "", ""],
    ["Ricky Council IV", "R IV", "4.78", "", "", ""],
    ["Robert Covington", "R Covington", "16.33", "", "", ""],
    ["Terquavion Smith", "T Smith", "7.2", "", "", ""],
    ["Tobias Harris", "T Harris", "35.4", "", "", ""],
    ["Tyrese Maxey", "T Maxey", "49.92", "", "", ""],
]

PHX = [
    ["Bol Bol", "B Bol", "9.41", "", "", ""],
    ["Bradley Beal", "B Beal", "32.86", "", "", ""],
    ["Chimezie Metu", "C Metu", "11.95", "", "", ""],
    ["Devin Booker", "D Booker", "50.68", "", "", ""],
    ["Drew Eubanks", "D Eubanks", "14.86", "", "", ""],
    ["Eric Gordon", "E Gordon", "26.99", "", "", ""],
    ["Grayson Allen", "G Allen", "30.87", "", "", ""],
    ["Jordan Goodwin", "J Goodwin", "14.52", "", "", ""],
    ["Josh Okogie", "J Okogie", "15.18", "", "", ""],
    ["Jusuf Nurkic", "J Nurkic", "34.54", "", "", ""],
    ["Keita Bates-Diop", "K Bates-Diop", "13.07", "", "", ""],
    ["Kevin Durant", "K Durant", "52.98", "", "", ""],
    ["Nassir Little", "N Little", "10.84", "", "", ""],
    ["Saben Lee", "S Lee", "7.07", "", "", ""],
    ["Udoka Azubuike", "U Azubuike", "7.67", "", "", ""],
    ["Yuta Watanabe", "Y Watanabe", "9.34", "", "", ""],
]

POR = [
    ["Anfernee Simons", "A Simons", "41.15", "", "", ""],
    ["Deandre Ayton", "D Ayton", "31.29", "", "", ""],
    ["Duop Reath", "D Reath", "20.68", "", "", ""],
    ["Ibou Badji", "I Badji", "10.38", "", "", ""],
    ["Ish Wainright", "I Wainright", "7.46", "", "", ""],
    ["Jabari Walker", "J Walker", "20.48", "", "", ""],
    ["Jamaree Bouyea", "J Bouyea", "4.29", "", "", ""],
    ["Jerami Grant", "J Grant", "36.04", "", "", ""],
    ["Justin Minaya", "J Minaya", "5.5", "", "", ""],
    ["Kris Murray", "K Murray", "9.76", "", "", ""],
    ["Malcolm Brogdon", "M Brogdon", "33.91", "", "", ""],
    ["Matisse Thybulle", "M Thybulle", "18.85", "", "", ""],
    ["Moses Brown", "M Brown", "9.52", "", "", ""],
    ["Rayan Rupert", "R Rupert", "6.11", "", "", ""],
    ["Robert Williams III", "R III", "21.56", "", "", ""],
    ["Scoot Henderson", "S Henderson", "25.13", "", "", ""],
    ["Shaedon Sharpe", "S Sharpe", "31.75", "", "", ""],
    ["Skylar Mays", "S Mays", "16.76", "", "", ""],
    ["Taze Moore", "T Moore", "3.05", "", "", ""],
    ["Toumani Camara", "T Camara", "19.04", "", "", ""],
]

SAC = [
    ["Alex Len", "A Len", "9.51", "", "", ""],
    ["Chris Duarte", "C Duarte", "9.61", "", "", ""],
    ["Colby Jones", "C Jones", "6.08", "", "", ""],
    ["Davion Mitchell", "D Mitchell", "8.75", "", "", ""],
    ["De'Aaron Fox", "D Fox", "50.0", "", "", ""],
    ["Domantas Sabonis", "D Sabonis", "49.5", "", "", ""],
    ["Filip Petrusev", "F Petrusev", "1.5", "", "", ""],
    ["Harrison Barnes", "H Barnes", "23.25", "", "", ""],
    ["JaVale McGee", "J McGee", "10.4", "", "", ""],
    ["Jalen Slawson", "J Slawson", "2.56", "", "", ""],
    ["Jordan Ford", "J Ford", "3.21", "", "", ""],
    ["Juan Toscano-Anderson", "J Toscano-Anderson", "3.46", "", "", ""],
    ["Keegan Murray", "K Murray", "33.68", "", "", ""],
    ["Keon Ellis", "K Ellis", "11.41", "", "", ""],
    ["Kessler Edwards", "K Edwards", "4.01", "", "", ""],
    ["Kevin Huerter", "K Huerter", "26.56", "", "", ""],
    ["Malik Monk", "M Monk", "31.57", "", "", ""],
    ["Sasha Vezenkov", "S Vezenkov", "13.42", "", "", ""],
    ["Trey Lyles", "T Lyles", "18.25", "", "", ""],
]

SAS = [
    ["Blake Wesley", "B Wesley", "10.04", "", "", ""],
    ["Cedi Osman", "C Osman", "16.9", "", "", ""],
    ["Charles Bassey", "C Bassey", "12.85", "", "", ""],
    ["Devin Vassell", "D Vassell", "36.12", "", "", ""],
    ["Devonte' Graham", "D Graham", "10.21", "", "", ""],
    ["Dominick Barlow", "D Barlow", "13.08", "", "", ""],
    ["Doug McDermott", "D McDermott", "12.72", "", "", ""],
    ["Jeremy Sochan", "J Sochan", "28.12", "", "", ""],
    ["Julian Champagnie", "J Champagnie", "15.66", "", "", ""],
    ["Keldon Johnson", "K Johnson", "34.23", "", "", ""],
    ["Malaki Branham", "M Branham", "16.35", "", "", ""],
    ["Mamadi Diakite", "M Diakite", "7.05", "", "", ""],
    ["Sandro Mamukelashvili", "S Mamukelashvili", "8.18", "", "", ""],
    ["Sidy Cissoko", "S Cissoko", "4.24", "", "", ""],
    ["Tre Jones", "T Jones", "25.54", "", "", ""],
    ["Victor Wembanyama", "V Wembanyama", "50.14", "", "", ""],
    ["Zach Collins", "Z Collins", "27.02", "", "", ""],
]

TOR = [
    ["Bruce Brown", "B Brown", "28.22", "", "", ""],
    ["Chris Boucher", "C Boucher", "14.3", "", "", ""],
    ["Dennis Schroder", "D Schroder", "30.84", "", "", ""],
    ["Garrett Temple", "G Temple", "2.94", "", "", ""],
    ["Gary Trent Jr.", "G Jr.", "23.59", "", "", ""],
    ["Gradey Dick", "G Dick", "10.19", "", "", ""],
    ["Immanuel Quickley", "I Quickley", "38.81", "", "", ""],
    ["Jakob Poeltl", "J Poeltl", "28.34", "", "", ""],
    ["Jalen McDaniels", "J McDaniels", "7.19", "", "", ""],
    ["Javon Freeman-Liberty", "J Freeman-Liberty", "1.6", "", "", ""],
    ["Jontay Porter", "J Porter", "17.95", "", "", ""],
    ["Jordan Nwora", "J Nwora", "21.22", "", "", ""],
    ["Kira Lewis Jr.", "K Jr.", "0.0", "", "", ""],
    ["Malachi Flynn", "M Flynn", "14.22", "", "", ""],
    ["Markquis Nowell", "M Nowell", "10.4", "", "", ""],
    ["OG Anunoby", "O Anunoby", "31.33", "", "", ""],
    ["Otto Porter Jr.", "O Jr.", "8.23", "", "", ""],
    ["Pascal Siakam", "P Siakam", "40.61", "", "", ""],
    ["Precious Achiuwa", "P Achiuwa", "19.98", "", "", ""],
    ["RJ Barrett", "R Barrett", "38.87", "", "", ""],
    ["Ron Harper Jr.", "R Jr.", "1.5", "", "", ""],
    ["Scottie Barnes", "S Barnes", "48.17", "", "", ""],
    ["Thaddeus Young", "T Young", "14.4", "", "", ""],
]

UTA = [
    ["Brice Sensabaugh", "B Sensabaugh", "3.61", "", "", ""],
    ["Collin Sexton", "C Sexton", "31.37", "", "", ""],
    ["John Collins", "J Collins", "30.28", "", "", ""],
    ["Johnny Juzang", "J Juzang", "1.5", "", "", ""],
    ["Jordan Clarkson", "J Clarkson", "31.93", "", "", ""],
    ["Kelly Olynyk", "K Olynyk", "23.67", "", "", ""],
    ["Keyonte George", "K George", "23.26", "", "", ""],
    ["Kris Dunn", "K Dunn", "19.18", "", "", ""],
    ["Lauri Markkanen", "L Markkanen", "46.44", "", "", ""],
    ["Luka Samanic", "L Samanic", "5.56", "", "", ""],
    ["Micah Potter", "M Potter", "2.4", "", "", ""],
    ["Ochai Agbaji", "O Agbaji", "14.15", "", "", ""],
    ["Omer Yurtseven", "O Yurtseven", "9.33", "", "", ""],
    ["Simone Fontecchio", "S Fontecchio", "21.2", "", "", ""],
    ["Talen Horton-Tucker", "T Horton-Tucker", "24.65", "", "", ""],
    ["Taylor Hendricks", "T Hendricks", "13.09", "", "", ""],
    ["Walker Kessler", "W Kessler", "27.18", "", "", ""],
]

WAS = [
    ["Anthony Gill", "A Gill", "4.96", "", "", ""],
    ["Bilal Coulibaly", "B Coulibaly", "21.5", "", "", ""],
    ["Corey Kispert", "C Kispert", "21.01", "", "", ""],
    ["Daniel Gafford", "D Gafford", "30.88", "", "", ""],
    ["Danilo Gallinari", "D Gallinari", "14.28", "", "", ""],
    ["Delon Wright", "D Wright", "15.9", "", "", ""],
    ["Deni Avdija", "D Avdija", "29.49", "", "", ""],
    ["Eugene Omoruyi", "E Omoruyi", "9.1", "", "", ""],
    ["Hamidou Diallo", "H Diallo", "5.45", "", "", ""],
    ["Jared Butler", "J Butler", "10.32", "", "", ""],
    ["Johnny Davis", "J Davis", "4.85", "", "", ""],
    ["Jordan Poole", "J Poole", "30.39", "", "", ""],
    ["Jules Bernard", "J Bernard", "2.16", "", "", ""],
    ["Kyle Kuzma", "K Kuzma", "40.75", "", "", ""],
    ["Landry Shamet", "L Shamet", "15.46", "", "", ""],
    ["Marvin Bagley III", "M III", "28.88", "", "", ""],
    ["Mike Muscala", "M Muscala", "11.22", "", "", ""],
    ["Patrick Baldwin Jr.", "P Jr.", "7.74", "", "", ""],
    ["Ryan Rollins", "R Rollins", "10.07", "", "", ""],
    ["Trey Jemison", "T Jemison", "0.1", "", "", ""],
    ["Tyus Jones", "T Jones", "31.73", "", "", ""],
]
